//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alarm_t
    {
        public long Alarm_Id { get; set; }
        public System.Guid Alarm_DeviceUid { get; set; }
        public System.Guid Alarm_Uid { get; set; }
        public string Alarm_Message { get; set; }
        public System.DateTime Alarm_Starttime { get; set; }
        public System.Guid Alarm_Type { get; set; }
        public Nullable<System.DateTime> Alarm_Endtime { get; set; }
        public int Alarm_Status { get; set; }
    }
}
