//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area_t
    {
        public int Ara_Id { get; set; }
        public System.Guid Ara_UId { get; set; }
        public string Ara_Code { get; set; }
        public string Ara_Name { get; set; }
        public string Ara_Description { get; set; }
        public int Ara_Level { get; set; }
        public Nullable<System.Guid> Ara_Up { get; set; }
        public int Ara_Enable { get; set; }
        public Nullable<decimal> Ara_Lat { get; set; }
        public Nullable<decimal> Ara_Lng { get; set; }
    }
}
