//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authority_t
    {
        public long Auth_Id { get; set; }
        public System.Guid Auth_Uid { get; set; }
        public string Auth_Name { get; set; }
        public string Auth_Description { get; set; }
        public string Auth_Action { get; set; }
        public int Auth_MenuNum { get; set; }
        public int Auth_Enable { get; set; }
    }
}
