//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceOperationCondition_t
    {
        public long Doc_Id { get; set; }
        public System.Guid Doc_UId { get; set; }
        public System.Guid Doc_FlowMeterUId { get; set; }
        public decimal Doc_MainBatteryStatus { get; set; }
        public decimal Doc_SecondaryBatteryStatus { get; set; }
        public decimal Doc_ModemBatteryStatus { get; set; }
        public decimal Doc_AntennaSignal { get; set; }
        public System.DateTime Doc_SendDt { get; set; }
        public System.DateTime Doc_ReceiveDt { get; set; }
        public System.DateTime Doc_CreateDt { get; set; }
    }
}
