//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowMeterStatus_t
    {
        public long FMS_Id { get; set; }
        public System.Guid FMS_DeviceUid { get; set; }
        public Nullable<decimal> FMS_FlowValue { get; set; }
        public decimal FMS_MainBatteryStatus { get; set; }
        public decimal FMS_SecondaryBatteryStatus { get; set; }
        public decimal FMS_ModemBatteryStatus { get; set; }
        public decimal FMS_AntennaSignal { get; set; }
        public System.DateTime FMS_UpdateDt { get; set; }
        public Nullable<int> FMS_IsTimeOverException { get; set; }
        public Nullable<int> FMS_IsMainBatteryException { get; set; }
        public Nullable<int> FMS_IsModemBatteryException { get; set; }
        public Nullable<int> FMS_ValueExceptionNum { get; set; }
    }
}
