//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowMeter_t
    {
        public long FM_Id { get; set; }
        public System.Guid FM_UId { get; set; }
        public string FM_AlarmThreshold { get; set; }
        public string FM_AlarmNumber { get; set; }
        public int FM_AlarmMode { get; set; }
        public Nullable<decimal> FM_Lat { get; set; }
        public Nullable<decimal> FM_Lng { get; set; }
        public int FM_Class { get; set; }
        public string FM_Code { get; set; }
        public string FM_Description { get; set; }
        public System.Guid FM_ParentFlowMeterUId { get; set; }
        public int FM_IsLeaf { get; set; }
        public int FM_Level { get; set; }
        public System.Guid FM_WaterConsumerUId { get; set; }
        public decimal FM_BatteryAlarmThreshold { get; set; }
        public decimal FM_ModemAlarmThreshold { get; set; }
        public int FM_Enable { get; set; }
        public string FM_DeviceAlarmNumber { get; set; }
        public Nullable<int> FM_AlarmTimeout { get; set; }
        public Nullable<int> FM_AlarmStatus { get; set; }
        public Nullable<int> FM_mLevel { get; set; }
        public Nullable<int> FM_FlowAlarmMode { get; set; }
        public Nullable<int> FM_FlowAlarmEnable { get; set; }
        public Nullable<decimal> FM_FlowAlarmThreshold { get; set; }
        public Nullable<System.DateTime> FM_FlowAlarmLasttime { get; set; }
        public string FM_FlowHourAlarmThreshold { get; set; }
        public Nullable<System.DateTime> FM_FlowCountLast { get; set; }
    }
}
