//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowHour_t
    {
        public long Flh_Id { get; set; }
        public Nullable<decimal> Flh_MaxValue { get; set; }
        public Nullable<decimal> Flh_MinValue { get; set; }
        public int Flh_Time { get; set; }
        public Nullable<decimal> Flh_TotalValue { get; set; }
        public Nullable<decimal> Flh_OriTotalValue { get; set; }
        public System.Guid Flh_FlowMeterUid { get; set; }
    }
}
