//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowCount_t
    {
        public long FC_Id { get; set; }
        public Nullable<System.Guid> FC_FlowMeterUId { get; set; }
        public Nullable<decimal> FC_MaxValue { get; set; }
        public Nullable<decimal> FC_MinValue { get; set; }
        public System.DateTime FC_StartTime { get; set; }
        public System.DateTime FC_EndTime { get; set; }
        public Nullable<decimal> FC_TotalValue { get; set; }
        public Nullable<decimal> FC_OriTotalValue { get; set; }
        public Nullable<System.Guid> FC_AFUId { get; set; }
        public int FC_Status { get; set; }
    }
}
