//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowDay_t
    {
        public long Fld_Id { get; set; }
        public decimal Fld_MaxValue { get; set; }
        public Nullable<decimal> Fld_MinValue { get; set; }
        public int Fld_Time { get; set; }
        public Nullable<decimal> Fld_TotalValue { get; set; }
        public Nullable<decimal> Fld_OriTotalValue { get; set; }
        public System.Guid Fld_FlowMeterUid { get; set; }
    }
}
