//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flow_t
    {
        public long Flw_Id { get; set; }
        public Nullable<System.Guid> Flw_FlowMeterUId { get; set; }
        public decimal Flw_Value { get; set; }
        public System.DateTime Flw_SendDt { get; set; }
        public System.DateTime Flw_ReceiveDt { get; set; }
        public System.DateTime Flw_CreateDt { get; set; }
        public string Flw_EmailCode { get; set; }
        public decimal Flw_TotalValue { get; set; }
    }
}
