//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowReport_t
    {
        public long FR_Id { get; set; }
        public System.DateTime FR_Update { get; set; }
        public System.Guid FR_FlowMeterUid { get; set; }
        public System.Guid FR_UserUid { get; set; }
        public Nullable<decimal> FR_LastReadValue { get; set; }
        public Nullable<decimal> FR_currentReadValue { get; set; }
        public Nullable<decimal> FR_LastMonthValue { get; set; }
        public Nullable<decimal> FR_CurrentMonthValue { get; set; }
        public Nullable<decimal> FR_LastYearMonthValue { get; set; }
        public string FR_Memo { get; set; }
        public Nullable<decimal> FR_MOM { get; set; }
        public Nullable<decimal> FR_YOY { get; set; }
    }
}
