//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class PressureHour_t
    {
        public long PH_Id { get; set; }
        public int PH_Time { get; set; }
        public System.Guid PH_PressureMeterUid { get; set; }
        public decimal PH_RealTimeValue { get; set; }
        public decimal PH_MaxValue { get; set; }
        public decimal PH_MinValue { get; set; }
        public decimal PH_AverageValue { get; set; }
    }
}
