//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class PressureMonth_t
    {
        public long PM_Id { get; set; }
        public int PM_Time { get; set; }
        public System.Guid PM_PressureMeterUid { get; set; }
        public decimal PM_MaxValue { get; set; }
        public decimal PM_MinValue { get; set; }
        public decimal PM_AverageValue { get; set; }
    }
}
