//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class PressureMeter_t
    {
        public long PM_Id { get; set; }
        public System.Guid PM_UId { get; set; }
        public decimal PM_Lat { get; set; }
        public decimal PM_Lng { get; set; }
        public string PM_Code { get; set; }
        public string PM_Description { get; set; }
        public Nullable<System.DateTime> PM_CountLast { get; set; }
    }
}
