//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class PressureMeterStatus_t
    {
        public long PMS_Id { get; set; }
        public System.Guid PMS_DeviceUid { get; set; }
        public decimal PMS_PressureValue { get; set; }
        public decimal PMS_MainBatteryStatus { get; set; }
        public decimal PMS_SecondaryBatteryStatus { get; set; }
        public decimal PMS_ModemBatteryStatus { get; set; }
        public decimal PMS_AntennaSignal { get; set; }
        public System.DateTime PMS_UpdateDt { get; set; }
        public Nullable<int> PMS_IsTimeOverException { get; set; }
        public Nullable<int> PMS_IsMainBatteryException { get; set; }
        public Nullable<int> PMS_IsModemBatteryException { get; set; }
        public Nullable<int> PMS_ValueExceptionNum { get; set; }
    }
}
