//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class PressureDay_t
    {
        public long PD_Id { get; set; }
        public int PD_Time { get; set; }
        public System.Guid PD_PressureMeterUid { get; set; }
        public decimal PD_MaxValue { get; set; }
        public decimal PD_MinValue { get; set; }
        public decimal PD_AverageValue { get; set; }
    }
}
