//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityMonth_t
    {
        public long QM_Id { get; set; }
        public System.Guid QM_QualityMeterUId { get; set; }
        public decimal QM_PH { get; set; }
        public decimal QM_MaxPH { get; set; }
        public decimal QM_MinPH { get; set; }
        public decimal QM_Chlorine { get; set; }
        public decimal QM_MaxChlorine { get; set; }
        public decimal QM_MinChlorine { get; set; }
        public decimal QM_Turbidity { get; set; }
        public decimal QM_MaxTurbidity { get; set; }
        public decimal QM_MinTurbidity { get; set; }
        public decimal QM_ORP { get; set; }
        public decimal QM_MaxORP { get; set; }
        public decimal QM_MinORP { get; set; }
        public int QM_Time { get; set; }
    }
}
