//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityHour_t
    {
        public long QH_Id { get; set; }
        public System.Guid QH_QualityMeterUId { get; set; }
        public decimal QH_Q1 { get; set; }
        public decimal QH_Q2 { get; set; }
        public decimal QH_Q3 { get; set; }
        public decimal QH_Q4 { get; set; }
        public decimal QH_T1 { get; set; }
        public decimal QH_T2 { get; set; }
        public decimal QH_T3 { get; set; }
        public decimal QH_T4 { get; set; }
        public Nullable<System.DateTime> QH_SendDt { get; set; }
        public Nullable<System.DateTime> QH_ReceiveDt { get; set; }
        public Nullable<System.DateTime> QH_CreateDt { get; set; }
    }
}
