//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quality_t
    {
        public long Qua_Id { get; set; }
        public System.Guid Qua_QualityMeterUId { get; set; }
        public decimal Qua_Q1 { get; set; }
        public decimal Qua_Q2 { get; set; }
        public decimal Qua_Q3 { get; set; }
        public decimal Qua_Q4 { get; set; }
        public decimal Qua_T1 { get; set; }
        public decimal Qua_T2 { get; set; }
        public decimal Qua_T3 { get; set; }
        public decimal Qua_T4 { get; set; }
        public System.DateTime Qua_SendDt { get; set; }
        public System.DateTime Qua_ReceiveDt { get; set; }
        public System.DateTime Qua_CreateDt { get; set; }
        public Nullable<System.Guid> Qua_UserUid { get; set; }
    }
}
