//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityDay_t
    {
        public long QD_Id { get; set; }
        public System.Guid QD_QualityMeterUId { get; set; }
        public decimal QD_Q1 { get; set; }
        public decimal QD_Q2 { get; set; }
        public decimal QD_Q3 { get; set; }
        public decimal QD_Q4 { get; set; }
        public decimal QD_T1 { get; set; }
        public decimal QD_T2 { get; set; }
        public decimal QD_T3 { get; set; }
        public decimal QD_T4 { get; set; }
        public System.DateTime QD_SendDt { get; set; }
        public System.DateTime QD_ReceiveDt { get; set; }
        public System.DateTime QD_CreateDt { get; set; }
    }
}
