//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityMeter_t
    {
        public long QM_Id { get; set; }
        public System.Guid QM_UId { get; set; }
        public decimal QM_Lat { get; set; }
        public decimal QM_Lng { get; set; }
        public string QM_Code { get; set; }
        public string QM_Description { get; set; }
        public Nullable<System.DateTime> QM_CountLast { get; set; }
        public Nullable<int> QM_MapId { get; set; }
        public Nullable<System.DateTime> QM_RecevieLast { get; set; }
    }
}
