//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityYear_t
    {
        public long QY_Id { get; set; }
        public System.Guid QY_QualityMeterUId { get; set; }
        public decimal QY_PH { get; set; }
        public decimal QY_MaxPH { get; set; }
        public decimal QY_MinPH { get; set; }
        public decimal QY_Chlorine { get; set; }
        public decimal QY_MaxChlorine { get; set; }
        public decimal QY_MinChlorine { get; set; }
        public decimal QY_Turbidity { get; set; }
        public decimal QY_MaxTurbidity { get; set; }
        public decimal QY_MinTurbidity { get; set; }
        public decimal QY_ORP { get; set; }
        public decimal QY_MaxORP { get; set; }
        public decimal QY_MinORP { get; set; }
        public int QY_Time { get; set; }
    }
}
