//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysInfo_t
    {
        public long Si_Id { get; set; }
        public string Si_InfoCode { get; set; }
        public Nullable<int> Si_IntInfo { get; set; }
        public string Si_VcInfo { get; set; }
        public string Si_TextInfo { get; set; }
        public Nullable<System.DateTime> Si_DtInfo { get; set; }
        public Nullable<System.DateTime> Si_ModifyDt { get; set; }
        public Nullable<System.Guid> Si_Editor { get; set; }
    }
}
