//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterPreview.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_t
    {
        public long Usr_Id { get; set; }
        public System.Guid Usr_UId { get; set; }
        public string Usr_Name { get; set; }
        public string Usr_Password { get; set; }
        public string Usr_Realname { get; set; }
        public string Usr_Memo { get; set; }
        public int Usr_Type { get; set; }
        public string Usr_Phone { get; set; }
        public string Usr_PhoneCode { get; set; }
        public System.DateTime Usr_PhoneCodeDt { get; set; }
    }
}
